- name: Set Prompt
  ansible.builtin.shell: set-prompt elk

- name: copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install elastic search
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed

- name: start elastic search
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: restarted
    enabled: yes

- name: install kibana
  ansible.builtin.dnf:
    name: kibana
    state: installed

- name: Update Kibana Config Port line
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.port: 5601'
    line: "server.port: 5601"

- name: Update Kibana Config IP line
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.host: localhost'
    line: "server.host: 0.0.0.0"

- name: Start Kibana
  ansible.builtin.systemd_service:
    name: kibana
    state: restarted

#Reset the password of the elastic built-in superuser with
#'/usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic'.

#Generate an enrollment token for Kibana instances with
#'/usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana'.

#verification for kibana:
#/usr/share/kibana/bin/kibana-verification-code

