format_version: 10
pipelines:
  ci-server:
    group: tools
    materials:
      git-4f9022f:
        git: https://github.com/anand-320/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:rsFNC5K8WN5aliy5fraRpQ==:NEaOhSKi7Ks9CW+vP19ih3f8aIcEKDzAn48vnkBQsvk=
    stages:
    - ansible:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            tasks:
              - exec: {command: ansible-playbook, arguments: [ "-i", "ci-server.janand.online,", "tools.yml", "-e", "tool_name=ci-server", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321" ], run_if: passed}

