format_version: 10
pipelines:
  elk:
    group: tools
    materials:
      git-4f9022f:
        git: https://github.com/anand-320/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                - exec: {command: ansible-playbook, arguments: [ "-i", "elk-internal.janand.online,", "tools.yml", "-e", "tool_name=elk", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321" ], run_if: passed}

