- name: jenkins Setup
  ansible.builtin.include_tasks:
    file: jenkins-setup.yaml
  when: jenkins_setup | bool

- name: jenkins Setup
  ansible.builtin.include_tasks:
    file: jenkins-jobs.yml
  when: jenkins_jobs | bool

