- name: set prompt
  ansible.builtin.shell: set-prompt jenkins

- name: Copy Jenkins repo file
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: install java
  ansible.builtin.dnf:
    name:
      -java-17-openjdk
      -fontconfig
      -jenkins
    state: installed

- name: start jenkins server
  ansible.builtin.systemd_service:
    name: jenkins
    state: restarted