- name: set name in prompt
  ansible.builtin.shell: set-prompt prometheus

- name: download prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes
    owner: bin

- name: copy prometheus
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service


- name: Start Prometheus Service
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: yes
    daemon-reload: yes